added solution
jazbassi1/pythonpractice pull request #5
Opened 2021-03-14 15:50 UTC by jazbassi1

added solution for iterables and iterations hackerrank

2021-03-15 13:05 UTC, manokhina commented on IterablesandIterators.py
> +from itertools import combinations
Could you provide the context for the problem? i.e. what is done and why

2021-03-15 13:06 UTC, manokhina requested changes
Please add context for the problem solved

2021-03-15 13:06 UTC, manokhina commented on IterablesandIterators.py
> +print('%.3f'%(len(r)/ len(c)))
empty line needed

2021-03-17 17:15 UTC, jazbassi1 commented on IterablesandIterators.py
> +from itertools import combinations
Changes made

2021-03-17 17:16 UTC, merged